### PR TITLE
Fix wrong jsdoc links

### LINKED ISSUE #67: Links to https://json-schema.org in the full API docs are broken
## 🐛 Bug Report

Links to https://json-schema.org in the full API docs are broken.

Screenshot 2020-05-01 at 14 51 24

I believe the it should be `[reference](link)`.

## To Reproduce

Click in any link pointing to the JSON Schema reference.

## Expected behavior

Links should work.

## Your Environment

Not applicable.

### PR DESCRIPTION
**Pull request by satazor**
Fixes #67

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by satazor** [comment]
@mcollina I've noticed that the links are still broken as we are pointing to https://json-schema.org/latest/json-schema-validation.html which redirects to https://json-schema.org/draft/2019-09/json-schema-validation.html, making all the hash tags to be lost (#xxxxx).

Can I change all the links to https://json-schema.org/draft/2019-09/json-schema-validation.html?

**Comment by mcollina** [comment]
ok for me

**Comment by Eomm** [comment]
> Can I change all the links to https://json-schema.org/draft/2019-09/json-schema-validation.html?

No, that version is not supported: it is draft 08 and we (like ajv) support draft 07!

I didn't find the right link, it should be hidden here https://json-schema.org/specification-links.html#draft-7

**Comment by aboutlo** [comment]
@satazor this is the draft7 reference page https://tools.ietf.org/id/draft-handrews-json-schema-validation-02.html (not nice URL). However, you can use as base URL.

**Comment by satazor** [comment]
@aboutlo It seems we are using 01: https://tools.ietf.org/html/draft-handrews-json-schema-01

For instance, in Array schema, `fluent-schema` uses `dependencies` from 01 while it was renamed to `dependentRequired` in 02.

Can I update to use https://tools.ietf.org/html/draft-handrews-json-schema-01?

**Comment by aboutlo** [comment]
nice catch @satazor, then yes it's `01`

**Comment by satazor** [comment]
This should be ready to be merged.

- I've standardized the position of links since some were at the top while others were in parameters. Now they are all at the top, except for `ifThen` and `ifThenElse`.

**Comment by satazor** [comment]
@mcollina no problem, and thanks for this lib!

**Pull request merged**
