### PR TITLE
Add tests against node 14.x

### PR DESCRIPTION
**Pull request by aboutlo**
Add node14.x in Travis

### CODE REVIEW

**Comment by aboutlo** [comment]
The only check running is now Snyk. Is Travis gone? 🤔

**Comment by aboutlo** [comment]
@Eomm I noticed just now that you raised this issue in #70 but I thought was a temp issue. Do we need to change something to have Travis back?

**Comment by aboutlo** [comment]
I just notice that Travis is gone in Ffastify itself ... so I guess GitHub actions is the new way: https://github.com/fastify/fastify/tree/master/.github

**Comment by Eomm** [comment]
Yeah, we are using actions everywhere right now

**Comment by aboutlo** [comment]
resolved here https://github.com/fastify/fluent-schema/pull/74

**Pull request closed without merging**
