### PR TITLE
fix: allow empty array as default value for a prop

### PR DESCRIPTION
**Pull request by salmanm**
Allow empty array as default value for a prop.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Eomm** [comment]
The tests are not failing (?!)

Checking the spec it seems this is a valid schema tho

```
{
    type: 'object',
    properties: {
      asd: {
        type: 'array',
        items: { type: 'integer' },
        default: []
      }
    }
  }
```

**Comment by salmanm** [comment]
@Eomm That's weird. It is failing on my machine 🤔 

image

**Comment by Eomm** [comment]
Oh, travis did not run 😕 
Anyway, it fails 👍 the case is good!

Would you like to fix it?

**Comment by salmanm** [comment]
Here you go, pushed a fix.

**Comment by Eomm** [comment]
cc @aboutlo

**Pull request merged**
