### PR TITLE
fixes typings for typescript usage (both CommonJS and ES6 modules)

### PR DESCRIPTION
**Pull request by dodiego**
The types are broken when using typescript or a a project with a jsconfig.json, this is related to https://github.com/fastify/fluent-schema/issues/62 and this PR solves that issue.

In addition to that, I added the package-lock.json to the project since it ensures the correct version of each dependency will be installed.

### CODE REVIEW

**Comment by mcollina** [comment]
Can you please remove package-lock? Thanks.

Also, can you add some sort of test so that we do not regress this?

**Comment by dodiego** [comment]
@mcollina I removed the package-lock.json and added a basic test file, the way it works now is much like [axios](https://github.com/axios/axios), requiring the module works (as before), but using `require('fluent-schema').default` returns the type definitions. It works with ES6 import as well.

**Comment by aboutlo** [comment]
LGTM but all my projects have "esModuleInterop": true 
Anyone use MS Code and can double-check if this helps for code hint as well? @jnv related to #59

**Comment by jnv** [comment]
> LGTM but all my projects have "esModuleInterop": true 
> Anyone use MS Code and can double-check if this helps for code hint as well? @jnv related to #59 

@javi11

**Pull request merged**
